task1 v1.0
YauheniLukashkin/YauheniLukashkin.github.io pull request #3
Opened 2017-03-13 17:50 UTC by YauheniLukashkin

2017-03-13 18:34 UTC, WebTownIP requested changes
there are some request changes and several features to try

2017-03-13 18:34 UTC, WebTownIP commented on css/main.css
> +  margin-left: 10%;
margins are not required here

2017-03-13 18:34 UTC, WebTownIP commented on css/main.css
> +  display: table;
it's one of the way, but you have only one line text
please think about another solution, thaks

2017-03-13 18:34 UTC, WebTownIP commented on css/main.css
> +.header_text {
look above

2017-03-13 18:34 UTC, WebTownIP commented on css/main.css
> +  width: 21%;
basically your page is static, so you are free to use fixed values
but % in this ok too, because % of 1200px

2017-03-13 18:34 UTC, WebTownIP commented on css/main.css
> +  height: 250px;
could you remove height from here and change height value in `.nav_block`? :)

2017-03-13 18:34 UTC, WebTownIP commented on index.html
> +      <nav class="container">
let's add light grey background to `nav` block
you will get bug

2017-03-13 18:34 UTC, WebTownIP commented on index.html
> +      <main class="container">
same

2017-03-13 18:34 UTC, WebTownIP commented on css/main.css
> +  min-width: 1200px;
don't you think it's copy paste?

2017-03-13 21:08 UTC, NikitaSedyx commented
![head_bug](https://cloud.githubusercontent.com/assets/12440608/23875390/570d35da-084a-11e7-9b0a-e1d1fc4ca9f6.png)

2017-03-13 21:10 UTC, NikitaSedyx requested changes
for now I see only two issues

2017-03-13 21:10 UTC, NikitaSedyx commented on index.html
> +      <main class="container">
is it required now?

2017-03-14 06:07 UTC, NikitaSedyx approved these changes

2017-03-14 07:21 UTC, merged